services:
  user_microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-microservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://user_db:3306/user_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=VerySecretCode
      - DEFAULT_EMAIL=admin@default.com
      - DEFAULT_PASSWORD=SuperSecretPassword
    volumes:
      - .:/app
    depends_on:
      user_db:
        condition: service_healthy
    networks:
      - pms-network

  user_db:
    image: mysql:8
    container_name: user-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - pms-network

volumes:
  mysql_user_data:
