services:
  gateway_microservice:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: gateway-microservice
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=VerySecretCode
    volumes:
      - .:/app
    networks:
      - pms-network
